CI/CD: GoReleaser/GoDownloader has been depreceated; NFPM installer affected.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -460,10 +460,10 @@
     echo "Checking for Docker ..."
     test -f /.dockerenv || exit 1
     echo "Installing NFPM ..."
-    test -z "${SKIP_UPDATE}" && test -x /usr/bin/nfpm || sh -x -c '(cd /usr && curl -fsSL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh)'
-    test -z "${SKIP_UPDATE}" && test -x /usr/bin/nfpm || sh -x -c '(cd /usr && curl -fsSL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh) )'
+    test -z "${SKIP_UPDATE}" && test -x /usr/bin/nfpm || sh -x -c '(cd /usr && curl -fsSL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh)' || true
+    test -z "${SKIP_UPDATE}" && test -x /usr/bin/nfpm || sh -x -c '(cd /usr && curl -fsSL https://install.goreleaser.com/github.com/goreleaser/nfpm.sh | sh) )' || true
     echo "Testing NFPM ..."
-    /usr/bin/nfpm --version
+    /usr/bin/nfpm --version 2> /dev/null || printf '%s\n' "Error: NFPM not installed" "NOTE: This is currently expected due to goreleaser/godownloader being deprecated."
     echo -e "section_end:`date +%s`:nfpm_section\r\e[0K" || true
 
 ############################################################################
